services:
  - type: web
    name: ingraynieris
    runtime: static
    routes:
      - type: header
        path: "/Ubermensch-Firmado.mobileconfig"
        headers:
          - key: "Content-Type"
            value: "application/x-apple-aspen-config"